/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String add_user = "assets/image/add_user.png";
  static const String arrow_down = "assets/image/arrow_down.png";
  static const String back = "assets/image/back.png";
  static const String checked_box = "assets/image/checked_box.png";
  static const String email = "assets/image/email.png";
  static const String icons8_popular_100 = "assets/image/icons8-popular-100.png";
  static const String icons8_top_rated_64 = "assets/image/icons8-top-rated-64.png";
  static const String icons8_upcoming_64 = "assets/image/icons8-upcoming-64.png";
  static const String mobile = "assets/image/mobile.png";
  static const String password = "assets/image/password.png";
  static const String Signika_Bold = "assets/fonts/Signika-Bold.ttf";
  static const String Signika_Light = "assets/fonts/Signika-Light.ttf";
  static const String Signika_Medium = "assets/fonts/Signika-Medium.ttf";
  static const String Signika_Regular = "assets/fonts/Signika-Regular.ttf";
  static const String Signika_SemiBold = "assets/fonts/Signika-SemiBold.ttf";
  static const String user = "assets/image/user.png";
}
